2024-04-13 06:00:55,673 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-13 06:01:16,287 ERROR: Exception on /edit_profile [POST] [in /home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/shield/projects/flask/flaskproj/app/routes.py", line 97, in edit_profile
    db.session.commit()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 598, in commit
    return self._proxied.commit()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1969, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1256, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1231, in _prepare_impl
    self.session.flush()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4312, in flush
    self._flush(objects)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush
    flush_context.execute()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 910, in _emit_update_statements
    c = connection.execute(
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 517, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('john', 'I am just testing this!!!', 1)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-04-14 19:24:10,633 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-14 19:24:36,007 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-16 17:57:59,646 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-16 18:05:44,902 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-16 18:06:25,352 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-16 18:15:00,639 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-18 04:26:08,115 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-18 04:39:00,759 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-18 04:39:32,825 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-18 04:40:48,130 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-18 04:44:07,944 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-18 04:47:08,426 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-19 16:59:29,508 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-19 17:01:00,960 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-19 17:01:18,794 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-19 17:08:00,176 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
2024-04-19 17:08:40,258 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
