2024-04-22 14:01:47,615 ERROR: Exception on /user/john [GET] [in /home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/shield/projects/flask/flaskproj/app/routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/shield/projects/flask/flaskproj/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/shield/projects/flask/flaskproj/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/shield/projects/flask/flaskproj/app/templates/user.html", line 20, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2024-04-22 14:01:57,614 ERROR: Exception on /user/john [GET] [in /home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/shield/projects/flask/flaskproj/app/routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/shield/projects/flask/flaskproj/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/shield/projects/flask/flaskproj/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/shield/projects/flask/flaskproj/app/templates/user.html", line 20, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2024-04-22 14:02:17,227 ERROR: Exception on /user/john [GET] [in /home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/shield/projects/flask/flaskproj/app/routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/shield/projects/flask/flaskproj/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/shield/projects/flask/flaskproj/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/shield/projects/flask/flaskproj/app/templates/user.html", line 20, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2024-04-22 14:03:21,784 ERROR: Exception on /user/susan [GET] [in /home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/shield/projects/flask/flaskproj/app/routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/shield/projects/flask/flaskproj/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/shield/projects/flask/flaskproj/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/shield/projects/flask/flaskproj/app/templates/user.html", line 20, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/shield/projects/flask/flaskproj/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2024-04-22 14:04:39,214 INFO: Flaskapp startup [in /home/shield/projects/flask/flaskproj/app/__init__.py:51]
